default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123
  host: 127.0.0.1
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: petCare_Development
  encoding: utf8

test:
  <<: *default
  database: = petCare_Development
  encoding: utf8

production:
  <<: *default
  database: petCare_Development
  encoding: utf8
  
  
  